/* 控制路由 */
var express = require('express')
var mongoose = require('../utils/db')
var router = express.Router()

var login = require('./login')
var register = require('./register')
var filter = require('./filter')
var follow = require('./follow')
var unfollow = require('./unfollow')
var getFollowing = require('./getFollowing')
var getFollower = require('./getFollower')
var getUserInfo = require('./getUserInfo')
var updateUserInfo = require('./updateUserInfo')
var createDynamic = require('./createDynamic')
var deleteDynamic = require('./deleteDynamic')
var getUserDynamic = require('./getUserDynamic')

router.post('/login', login)
router.post('/register', register)
router.post('/*', filter)
router.post('/follow', follow)
router.post('/unfollow', unfollow)
router.get('/getFollowing', getFollowing)
router.get('/getFollower', getFollower)
router.get('/getUserInfo', getUserInfo)
router.post('/updateUserInfo', updateUserInfo)
router.post('/createDynamic', createDynamic)
router.post('/deleteDynamic', deleteDynamic)
router.get('/getUserDynamic', getUserDynamic)

module.exports = router