/* 控制路由 */
var express = require('express')
var mongoose = require('../utils/db')
var router = express.Router()

var login = require('./login')
var register = require('./register')
var filter = require('./filter')
var follow = require('./follow')
var unfollow = require('./unfollow')
var getFollowing = require('./getFollowing')
var getFollower = require('./getFollower')
var getUserInfo = require('./getUserInfo')
var updateUserInfo = require('./updateUserInfo')
var createDynamic = require('./createDynamic')
var deleteDynamic = require('./deleteDynamic')
var getAllUserDynamic = require('./getAllUserDynamic')
var getUserDynamic = require('./getUserDynamic')
var favDynamic = require('./favDynamic')
var commitDynamic = require('./commitDynamic')
var forwardDynamic = require('./forwardDynamic')
var getDynamicDetail = require('./getDynamicDetail')
var getAllUserActivity = require('./getAllUserActivity')
var recommendedUsers = require('./recommendedUsers')

router.post('/login', login)
router.post('/register', register)
router.post('/*', filter)
router.post('/follow', follow)
router.post('/unfollow', unfollow)
router.get('/getFollowing', getFollowing)
router.get('/getFollower', getFollower)
router.get('/getUserInfo', getUserInfo)
router.post('/updateUserInfo', updateUserInfo)
router.post('/createDynamic', createDynamic)
router.post('/deleteDynamic', deleteDynamic)
router.get('/getAllUserDynamic', getAllUserDynamic)
router.get('/getUserDynamic', getUserDynamic)
router.post('/favDynamic', favDynamic)
router.post('/commitDynamic', commitDynamic)
router.post('/forwardDynamic', forwardDynamic)
router.get('/getDynamicDetail', getDynamicDetail)
router.get('/getAllUserActivity', getAllUserActivity)
router.get('/recommendedUsers', recommendedUsers)

module.exports = router